# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sBDJwFP04ukRyytLjCHeLVAyqixuLvjI
"""

# Vamos a generar una lista vacia

L = []

range(10)

for i in range(10):
 print(i)

L.append(5)
L

len([2,4,6,8])

Pares = [i for i in range(1,100) if i%2==0]
Pares

odd = [i for i in range(1,100) if i%2==1]
odd

import random

# Generar 100 números aleatorios del 1 al 10
numeros_aleatorios = [random.randint(1, 10) for _ in range(100)]

# Filtrar solo los números pares
numeros_pares = [num for num in numeros_aleatorios if num % 2 == 0]

print(numeros_aleatorios)
print(numeros_pares)